name: deepseek_rag
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aiofiles=24.1.0
  - annotated-doc=0.0.4
  - aom=3.12.1
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.2.0
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - dav1d=1.2.1
  - distro=1.9.0
  - expat=2.7.3
  - ffmpeg=6.1.1
  - ffmpy=0.3.0
  - filelock=3.20.0
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fsspec=2025.10.0
  - gradio=5.49.1
  - gradio-client=1.13.3
  - graphite2=1.3.14
  - groovy-python=0.1.2
  - h11=0.16.0
  - harfbuzz=10.2.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.34.4
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - jiter=0.12.0
  - jpeg=9f
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - langchain-openai=0.3.16
  - langchain-text-splitters=0.3.11
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.84.4
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.50
  - libtheora=1.2.0
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - mdurl=0.1.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openjpeg=2.5.2
  - openssl=3.0.18
  - orjson=3.11.4
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pip=25.3
  - pixman=0.46.4
  - pycparser=2.23
  - pydantic-core=2.33.2
  - pydub=0.25.1
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0post0
  - python-multipart=0.0.20
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyyaml=6.0.3
  - requests=2.32.5
  - requests-toolbelt=1.0.0
  - rich=14.2.0
  - ruff=0.12.0
  - safehttpx=0.1.7
  - semantic_version=2.10.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - sqlite=3.51.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tenacity=9.1.2
  - tk=8.6.15
  - tomlkit=0.13.3
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - websockets=15.0.1
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - build==1.3.0
      - cachetools==6.2.2
      - chromadb==1.3.5
      - click==8.3.1
      - coloredlogs==15.0.1
      - datasets==4.4.1
      - dill==0.4.0
      - durationpy==0.10
      - fastapi==0.122.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - google-auth==2.43.0
      - googleapis-common-protos==1.72.0
      - groq==0.36.0
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - httptools==0.7.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kubernetes==34.1.0
      - langchain==1.1.0
      - langchain-chroma==1.0.0
      - langchain-core==1.1.0
      - langchain-huggingface==1.1.0
      - langgraph==1.0.4
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.10
      - langsmith==0.4.48
      - markupsafe==3.0.3
      - mmh3==5.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.6
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - openai==2.8.1
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-otlp-proto-common==1.38.0
      - opentelemetry-exporter-otlp-proto-grpc==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - ormsgpack==1.12.0
      - overrides==7.7.0
      - pillow==12.0.0
      - posthog==5.4.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pydantic==2.12.5
      - pymupdf==1.26.6
      - pypdf2==3.0.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dotenv==1.2.1
      - referencing==0.37.0
      - regex==2025.11.3
      - replicate==1.0.7
      - requests-oauthlib==2.0.0
      - rpds-py==0.29.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentence-transformers==5.1.2
      - sniffio==1.3.1
      - starlette==0.50.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - transformers==4.57.3
      - typer==0.20.0
      - urllib3==2.3.0
      - uvicorn==0.38.0
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: C:\Users\Admin\anaconda3\envs\deepseek_rag
